version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: monthly
    assignees:
      - anton-yurchenko
    labels:
      - dependencies

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    target-branch: master
    assignees:
      - anton-yurchenko
      - ihor-kanivets
